# Generated by Django 5.2.16 on 2026-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcircleauth',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
