# Generated by Django 5.2.16 on 2026-08-05 17:51

from django.db import migrations, models


CANONICAL_USER_ID = '7593262e-3352-40bd-b5d9-7bcb21d1a8d6'
CANONICAL_CIRCLE_SSO_USER_ID = '0067ba7e-ad12-5919-84eb-531f46d1f370'


def migrate_canonical_google_identity(apps, schema_editor):
    ExternalIdentity = apps.get_model('accounts', 'ExternalIdentity')
    User = apps.get_model('accounts', 'User')
    WalletAccount = apps.get_model('wallets', 'WalletAccount')

    # A new/empty installation has no production identity to migrate.
    if not User.objects.filter(pk=CANONICAL_USER_ID).exists():
        return

    wallets = list(WalletAccount.objects.filter(user_id=CANONICAL_USER_ID))
    if len(wallets) != 1:
        raise RuntimeError('Canonical Google identity migration requires exactly one proven local wallet.')
    wallet = wallets[0]

    legacy = ExternalIdentity.objects.filter(
        user_id=CANONICAL_USER_ID,
        provider='CIRCLE',
        provider_user_id=f'wallet:{wallet.circle_wallet_id}',
    ).first()
    current = ExternalIdentity.objects.filter(
        provider='CIRCLE_SSO_GOOGLE',
        provider_user_id=CANONICAL_CIRCLE_SSO_USER_ID,
    ).first()
    if current:
        if str(current.user_id) != CANONICAL_USER_ID:
            raise RuntimeError('Canonical Circle SSO identity is already bound to another Veyra user.')
        if legacy and legacy.pk != current.pk:
            raise RuntimeError('Both legacy and Google SSO identities exist; refusing ambiguous migration.')
        return
    if not legacy:
        raise RuntimeError('Canonical legacy wallet identity could not be proven; refusing migration.')

    legacy.provider = 'CIRCLE_SSO_GOOGLE'
    legacy.provider_user_id = CANONICAL_CIRCLE_SSO_USER_ID
    legacy.save(update_fields=['provider', 'provider_user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentownerprofile'),
        ('wallets', '0003_walletaccount_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(choices=[('CIRCLE', 'Circle (legacy wallet key)'), ('CIRCLE_SSO_GOOGLE', 'Circle SSO (Google)')], max_length=20),
        ),
        migrations.RunPython(migrate_canonical_google_identity, migrations.RunPython.noop),
    ]
