# Generated by Django 5.2.16 on 2026-07-21 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('workers', '0003_workertestassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerJobQueueItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUEUED', 'Queued for claim'), ('DEFERRED', 'Deferred'), ('INELIGIBLE', 'Ineligible'), ('STALE', 'No longer open'), ('CLAIM_PENDING', 'Claim pending'), ('CLAIMED', 'Claimed'), ('EXECUTING', 'Executing'), ('SUBMISSION_PENDING', 'Submission pending'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DISCOVERED', max_length=32)),
                ('source', models.CharField(choices=[('FAST_PATH', 'JobCreated fast path'), ('RECONCILIATION', 'Periodic reconciliation'), ('MANUAL', 'Manual discovery')], default='RECONCILIATION', max_length=24)),
                ('eligibility_passed', models.BooleanField(default=False)),
                ('eligibility_code', models.CharField(blank=True, max_length=64)),
                ('eligibility_detail', models.CharField(blank=True, max_length=300)),
                ('priority_score', models.IntegerField(default=0)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('onchain_status', models.CharField(blank=True, max_length=24)),
                ('onchain_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_queue_items', to='jobs.veyrajob')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_queue_items', to='workers.workeragent')),
            ],
            options={
                'ordering': ['-priority_score', 'created_at'],
                'indexes': [models.Index(fields=['worker', 'status'], name='workers_wor_worker__6f8829_idx'), models.Index(fields=['status', 'priority_score'], name='workers_wor_status_49c424_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'job'), name='uniq_worker_job_queue_item')],
            },
        ),
    ]
