# Generated by Django 5.2.16 on 2026-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_workerjobqueueitem_claim_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_baseline_test_command',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_baseline_test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_baseline_test_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_branch_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_changed_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_commit_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_engine_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_failure_stage',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_post_test_command',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_post_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_pull_request_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_pull_request_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='execution_workspace_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_arc_transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_circle_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_circle_transaction_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_commit_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_deliverable_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_failure_stage',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_receipt_block_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='submission_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
