# Generated by Django 5.2.16 on 2026-07-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_unique_agent_operational_wallet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runneragentbinding',
            new_name='workers_run_runner__855191_idx',
            old_name='workers_run_runner__584890_idx',
        ),
        migrations.RenameIndex(
            model_name='runneragentbinding',
            new_name='workers_run_worker__1d6023_idx',
            old_name='workers_run_worker__7e6036_idx',
        ),
        migrations.RenameIndex(
            model_name='runnerdevice',
            new_name='workers_run_owner_u_e8d10a_idx',
            old_name='workers_run_owner_u_1f2ed2_idx',
        ),
        migrations.RenameIndex(
            model_name='runnerdevice',
            new_name='workers_run_last_se_66965d_idx',
            old_name='workers_run_last_se_72f412_idx',
        ),
        migrations.RenameIndex(
            model_name='runnerpairingcode',
            new_name='workers_run_worker__0c6049_idx',
            old_name='workers_run_worker__b8222f_idx',
        ),
        migrations.RenameIndex(
            model_name='runnerpairingcode',
            new_name='workers_run_owner_u_eba52c_idx',
            old_name='workers_run_owner_u_071f0e_idx',
        ),
    ]
