from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from common.models import AuditLog
from workers.agent_provisioning import AgentProvisioningError, provision_agent
from workers.circle_wallet import WorkerWalletProvisioningError, provision_worker_wallet
from workers.models import HostedAgentConnection, WorkerAgent
from workers.permissions import IsAgentOwner
from workers.runtime_status import runtime_snapshot
from workers.serializers import AgentOwnerWorkerSerializer
from workers.withdrawals import (
    AgentWithdrawalError,
    create_withdrawal,
    reconcile_withdrawal,
    wallet_snapshot,
    withdrawal_public,
)


class AgentOwnerWorkerViewSet(viewsets.ModelViewSet):
    """Owner-scoped control-plane API for externally hosted agents.

    This API never accepts or exposes the owner's AI provider API key. The
    owner pastes only the one-time Veyra connection link generated by the
    hosted runtime.
    """

    serializer_class = AgentOwnerWorkerSerializer
    permission_classes = [IsAgentOwner]
    http_method_names = ["get", "post", "patch", "head", "options"]

    def get_queryset(self):
        queryset = WorkerAgent.objects.select_related(
            "owner_user",
            "hosted_connection",
            "runtime_binding__runner",
        ).filter(owner_type=WorkerAgent.OwnerType.EXTERNAL)
        user = self.request.user
        if user.is_staff or user.is_superuser:
            return queryset
        return queryset.filter(owner_user=user)

    def perform_create(self, serializer):
        worker = serializer.save()
        AuditLog.objects.create(
            actor=self.request.user,
            action="AGENT_CREATED_AND_PROVISIONED",
            resource_type="WorkerAgent",
            resource_id=str(worker.id),
            metadata={
                "status": worker.status,
                "provisioning_stage": worker.provisioning_stage,
                "runtime_mode": "OWNER_HOSTED",
            },
        )

    def perform_update(self, serializer):
        worker = serializer.save()
        AuditLog.objects.create(
            actor=self.request.user,
            action="AGENT_PROFILE_UPDATED",
            resource_type="WorkerAgent",
            resource_id=str(worker.id),
        )

    @action(detail=True, methods=["post"], url_path="provision")
    def provision(self, request, pk=None):
        """Retry automatic runtime, wallet, and contract provisioning safely."""

        worker = self.get_object()
        connection_link = str(request.data.get("connection_link") or "").strip()
        try:
            result = provision_agent(
                worker,
                connection_link=connection_link or None,
            )
        except AgentProvisioningError as exc:
            worker.refresh_from_db()
            AuditLog.objects.create(
                actor=request.user,
                action="AGENT_PROVISIONING_FAILED",
                resource_type="WorkerAgent",
                resource_id=str(worker.id),
                metadata={
                    "stage": worker.provisioning_stage,
                    "status": worker.status,
                },
            )
            return Response(
                {
                    "detail": str(exc),
                    "agent": self.get_serializer(worker).data,
                },
                status=status.HTTP_409_CONFLICT,
            )

        worker.refresh_from_db()
        AuditLog.objects.create(
            actor=request.user,
            action="AGENT_PROVISIONING_COMPLETED",
            resource_type="WorkerAgent",
            resource_id=str(worker.id),
            metadata={
                "stage": result.stage,
                "status": result.status,
                "runtime_connected": result.runtime_connected,
                "wallet_ready": result.wallet_ready,
                "contract_authorised": result.contract_authorised,
            },
        )
        return Response({"agent": self.get_serializer(worker).data})

    @action(detail=True, methods=["get"], url_path="runtime/status")
    def runtime_status(self, request, pk=None):
        worker = self.get_object()
        return Response({"runtime": runtime_snapshot(worker)})

    @action(detail=True, methods=["post"], url_path="runtime/disconnect")
    def disconnect_runtime(self, request, pk=None):
        worker = self.get_object()
        try:
            connection = worker.hosted_connection
        except HostedAgentConnection.DoesNotExist:
            return Response(
                {"detail": "This agent has no hosted runtime connection."},
                status=status.HTTP_409_CONFLICT,
            )

        connection.status = HostedAgentConnection.Status.REVOKED
        connection.revoked_at = timezone.now()
        connection.last_error = "Disconnected by the agent owner."
        connection.save(
            update_fields=[
                "status",
                "revoked_at",
                "last_error",
                "updated_at",
            ]
        )
        worker.engine_connected = False
        worker.engine_last_error = "Hosted runtime disconnected by owner."
        worker.provisioning_stage = "RUNTIME_DISCONNECTED"
        worker.provisioning_error = worker.engine_last_error
        worker.status = WorkerAgent.Status.CONNECTION_FAILED
        worker.save(
            update_fields=[
                "engine_connected",
                "engine_last_error",
                "provisioning_stage",
                "provisioning_error",
                "status",
                "updated_at",
            ]
        )
        AuditLog.objects.create(
            actor=request.user,
            action="AGENT_RUNTIME_DISCONNECTED",
            resource_type="WorkerAgent",
            resource_id=str(worker.id),
        )
        return Response({"agent": self.get_serializer(worker).data})


    @action(detail=True, methods=["get"], url_path="wallet")
    def wallet(self, request, pk=None):
        worker = self.get_object()
        try:
            return Response({"wallet": wallet_snapshot(worker, request.user)})
        except AgentWithdrawalError as exc:
            return Response({"detail": str(exc)}, status=status.HTTP_503_SERVICE_UNAVAILABLE)

    @action(detail=True, methods=["get"], url_path="withdrawals")
    def withdrawals(self, request, pk=None):
        worker = self.get_object()
        records = list(worker.withdrawals.order_by("-created_at")[:25])
        if records and records[0].circle_transaction_id:
            try:
                records[0] = reconcile_withdrawal(records[0])
            except AgentWithdrawalError:
                pass
        return Response({"withdrawals": [withdrawal_public(value) for value in records]})

    @action(detail=True, methods=["post"], url_path="withdraw")
    def withdraw(self, request, pk=None):
        worker = self.get_object()
        try:
            withdrawal = create_withdrawal(
                worker=worker,
                owner=request.user,
                destination_address=request.data.get("destination_address"),
                amount_usdc=request.data.get("amount_usdc"),
            )
        except AgentWithdrawalError as exc:
            return Response({"detail": str(exc)}, status=status.HTTP_409_CONFLICT)
        return Response(
            {
                "withdrawal": withdrawal_public(withdrawal),
                "wallet": wallet_snapshot(worker, request.user, reconcile=False),
            },
            status=status.HTTP_202_ACCEPTED,
        )

    @action(detail=True, methods=["post"], url_path="create-wallet")
    def create_wallet(self, request, pk=None):
        """Recovery-only endpoint retained for older clients.

        New agent creation calls this operation automatically through the
        provision endpoint.
        """

        worker = self.get_object()
        try:
            result = provision_worker_wallet(worker)
        except WorkerWalletProvisioningError as exc:
            return Response(
                {"detail": str(exc)},
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        worker.refresh_from_db()
        AuditLog.objects.create(
            actor=request.user,
            action="AGENT_WALLET_CREATED" if result.created else "AGENT_WALLET_REUSED",
            resource_type="WorkerAgent",
            resource_id=str(worker.id),
            metadata={
                "wallet_role": "AGENT_OPERATIONAL",
                "custody_type": "DEVELOPER_CONTROLLED",
                "blockchain": result.blockchain,
            },
        )
        return Response(
            {
                "wallet": {
                    "address": result.address,
                    "blockchain": result.blockchain,
                    "account_type": result.account_type,
                    "created": result.created,
                },
                "agent": self.get_serializer(worker).data,
            },
            status=status.HTTP_201_CREATED if result.created else status.HTTP_200_OK,
        )
