# Generated by Django 5.2.16 on 2026-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveBigIntegerField()),
                ('contract_address', models.CharField(max_length=42)),
                ('last_scanned_block', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chain_id', 'contract_address'), name='uniq_indexer_cursor')],
            },
        ),
    ]
