# Generated by Django 5.2.16 on 2026-07-18 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_id', models.PositiveBigIntegerField()),
                ('contract_address', models.CharField(max_length=42)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('log_index', models.PositiveIntegerField()),
                ('block_number', models.PositiveBigIntegerField()),
                ('event_name', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['block_number', 'log_index'],
                'constraints': [models.UniqueConstraint(fields=('chain_id', 'contract_address', 'transaction_hash', 'log_index'), name='uniq_arc_event')],
            },
        ),
        migrations.CreateModel(
            name='JobDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for review'), ('LOCKED', 'Locked for funding'), ('FUNDING', 'Funding'), ('FUNDED', 'Funded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('github_issue_url', models.URLField()),
                ('repository_owner', models.CharField(max_length=120)),
                ('repository_name', models.CharField(max_length=120)),
                ('target_branch', models.CharField(default='main', max_length=120)),
                ('issue_number', models.PositiveBigIntegerField()),
                ('issue_title', models.CharField(max_length=240)),
                ('issue_body', models.TextField(blank=True)),
                ('budget_usdc', models.DecimalField(decimal_places=6, max_digits=30)),
                ('deadline', models.DateTimeField()),
                ('acceptance_criteria', models.JSONField(default=list)),
                ('advanced_options', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFundingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_commitment', models.JSONField()),
                ('task_commitment', models.JSONField()),
                ('policy_commitment', models.JSONField()),
                ('repository_hash', models.CharField(max_length=66)),
                ('task_hash', models.CharField(max_length=66)),
                ('policy_hash', models.CharField(max_length=66)),
                ('budget_atomic', models.DecimalField(decimal_places=0, max_digits=40)),
                ('expires_at', models.PositiveBigIntegerField()),
                ('verifier_address', models.CharField(max_length=42)),
                ('invited_provider_address', models.CharField(max_length=42)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funding_snapshot', to='jobs.jobdraft')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VeyraJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onchain_job_id', models.PositiveBigIntegerField(unique=True)),
                ('status', models.CharField(max_length=24)),
                ('client_status', models.CharField(max_length=32)),
                ('client_address', models.CharField(max_length=42)),
                ('invited_provider_address', models.CharField(max_length=42)),
                ('provider_address', models.CharField(blank=True, max_length=42)),
                ('verifier_address', models.CharField(max_length=42)),
                ('budget_atomic', models.DecimalField(decimal_places=0, max_digits=40)),
                ('expires_at', models.PositiveBigIntegerField()),
                ('claim_deadline', models.PositiveBigIntegerField(default=0)),
                ('repository_hash', models.CharField(max_length=66)),
                ('task_hash', models.CharField(max_length=66)),
                ('policy_hash', models.CharField(max_length=66)),
                ('deliverable_hash', models.CharField(blank=True, max_length=66)),
                ('commit_hash', models.CharField(blank=True, max_length=66)),
                ('pull_request_number', models.PositiveBigIntegerField(default=0)),
                ('report_hash', models.CharField(blank=True, max_length=66)),
                ('evidence_hash', models.CharField(blank=True, max_length=66)),
                ('rejection_reason_hash', models.CharField(blank=True, max_length=66)),
                ('creation_tx_hash', models.CharField(blank=True, max_length=66)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veyra_jobs', to=settings.AUTH_USER_MODEL)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='jobs.jobdraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobdraft',
            index=models.Index(fields=['client', 'status'], name='jobs_jobdra_client__83bc10_idx'),
        ),
        migrations.AddIndex(
            model_name='veyrajob',
            index=models.Index(fields=['client', 'client_status'], name='jobs_veyraj_client__fb29dc_idx'),
        ),
    ]
