# Generated by Django 5.2.16 on 2026-07-21 09:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('owner_type', models.CharField(choices=[('VEYRA', 'Veyra'), ('EXTERNAL', 'External owner')], default='VEYRA', max_length=16)),
                ('status', models.CharField(choices=[('SETUP_REQUIRED', 'Setup required'), ('PROFILE_READY', 'Profile ready'), ('ENGINE_CONNECTED', 'Engine connected'), ('WALLET_READY', 'Wallet ready'), ('PAYOUT_READY', 'Payout wallet ready'), ('GITHUB_READY', 'GitHub ready'), ('AUTHORISATION_PENDING', 'Authorisation pending'), ('TESTING', 'Test assignment running'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended')], default='SETUP_REQUIRED', max_length=32)),
                ('skills', models.JSONField(default=list)),
                ('minimum_budget_usdc', models.DecimalField(decimal_places=6, default='1.000000', max_digits=30)),
                ('maximum_active_jobs', models.PositiveSmallIntegerField(default=1)),
                ('repository_strategy', models.CharField(choices=[('FORK_PR', 'Fork and pull request')], default='FORK_PR', max_length=24)),
                ('engine_provider', models.CharField(choices=[('OPENCODE', 'OpenCode'), ('CUSTOM', 'Custom worker runtime')], default='OPENCODE', max_length=24)),
                ('engine_model', models.CharField(default='zai-org/glm-5.2', max_length=160)),
                ('engine_connected', models.BooleanField(default=False)),
                ('circle_wallet_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('circle_wallet_set_id', models.CharField(blank=True, max_length=80)),
                ('worker_wallet_address', models.CharField(blank=True, max_length=42, validators=[django.core.validators.RegexValidator(message='Enter a valid EVM wallet address.', regex='^0x[a-fA-F0-9]{40}$')])),
                ('wallet_blockchain', models.CharField(default='ARC-TESTNET', max_length=32)),
                ('wallet_account_type', models.CharField(default='SCA', max_length=8)),
                ('payout_wallet_address', models.CharField(blank=True, max_length=42, validators=[django.core.validators.RegexValidator(message='Enter a valid EVM wallet address.', regex='^0x[a-fA-F0-9]{40}$')])),
                ('github_username', models.CharField(blank=True, max_length=80)),
                ('github_connected', models.BooleanField(default=False)),
                ('contract_authorised', models.BooleanField(default=False)),
                ('test_assignment_passed', models.BooleanField(default=False)),
                ('discovery_enabled', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='workers_wor_status_ea4da0_idx'), models.Index(fields=['owner_type', 'status'], name='workers_wor_owner_t_613c97_idx')],
            },
        ),
    ]