# Generated by Django 5.2.16 on 2026-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_workerjobqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='github_freshness_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='github_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjobqueueitem',
            name='github_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workerjobqueueitem',
            name='status',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUEUED', 'Queued for claim'), ('DEFERRED', 'Deferred'), ('INELIGIBLE', 'Ineligible'), ('STALE', 'No longer open'), ('BLOCKED', 'Blocked by task freshness guard'), ('DUPLICATE', 'Duplicate repository issue'), ('CLAIM_PENDING', 'Claim pending'), ('CLAIMED', 'Claimed'), ('EXECUTING', 'Executing'), ('SUBMISSION_PENDING', 'Submission pending'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DISCOVERED', max_length=32),
        ),
    ]
