# Generated by Django 5.2 on 2026-07-21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0005_workerjobqueueitem_github_freshness_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_arc_transaction_hash",
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_circle_state",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_circle_transaction_id",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_failure_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_failure_stage",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_idempotency_key",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_receipt_block_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerjobqueueitem",
            name="claim_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
