# Generated by Django 5.2 for Veyra Phase 1 Step 2.

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0008_agent_owner_profile_and_work_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("device_address", models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid EVM wallet address.", regex=r"^0x[a-fA-F0-9]{40}$")])),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")], default="ACTIVE", max_length=16)),
                ("runner_version", models.CharField(blank=True, max_length=64)),
                ("os_name", models.CharField(blank=True, max_length=80)),
                ("os_version", models.CharField(blank=True, max_length=120)),
                ("architecture", models.CharField(blank=True, max_length=40)),
                ("python_version", models.CharField(blank=True, max_length=40)),
                ("health", models.CharField(choices=[("HEALTHY", "Healthy"), ("UNHEALTHY", "Unhealthy")], default="UNHEALTHY", max_length=16)),
                ("health_message", models.CharField(blank=True, max_length=240)),
                ("tools", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("owner_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runner_devices", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "created_at"]},
        ),
        migrations.CreateModel(
            name="RunnerPairingCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("owner_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runner_pairing_codes", to=settings.AUTH_USER_MODEL)),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runtime_pairing_codes", to="workers.workeragent")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RunnerAgentBinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")], default="ACTIVE", max_length=16)),
                ("paired_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("runner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_bindings", to="workers.runnerdevice")),
                ("worker", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="runtime_binding", to="workers.workeragent")),
            ],
            options={"ordering": ["-paired_at"]},
        ),
        migrations.AddIndex(
            model_name="runnerdevice",
            index=models.Index(fields=["owner_user", "status"], name="workers_run_owner_u_1f2ed2_idx"),
        ),
        migrations.AddIndex(
            model_name="runnerdevice",
            index=models.Index(fields=["last_seen_at"], name="workers_run_last_se_72f412_idx"),
        ),
        migrations.AddIndex(
            model_name="runnerpairingcode",
            index=models.Index(fields=["worker", "expires_at"], name="workers_run_worker__b8222f_idx"),
        ),
        migrations.AddIndex(
            model_name="runnerpairingcode",
            index=models.Index(fields=["owner_user", "expires_at"], name="workers_run_owner_u_071f0e_idx"),
        ),
        migrations.AddIndex(
            model_name="runneragentbinding",
            index=models.Index(fields=["runner", "status"], name="workers_run_runner__584890_idx"),
        ),
        migrations.AddIndex(
            model_name="runneragentbinding",
            index=models.Index(fields=["worker", "status"], name="workers_run_worker__7e6036_idx"),
        ),
    ]
