# Generated by Django 5.2.16 on 2026-07-18 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('circle_wallet_id', models.CharField(max_length=64, unique=True)),
                ('wallet_set_id', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(max_length=42)),
                ('blockchain', models.CharField(max_length=40)),
                ('account_type', models.CharField(default='SCA', max_length=16)),
                ('custody_type', models.CharField(default='USER_CONTROLLED', max_length=32)),
                ('status', models.CharField(default='LIVE', max_length=24)),
                ('last_usdc_balance', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('last_balance_sync_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CircleTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('WALLET_CREATE', 'Wallet create'), ('USDC_APPROVAL', 'USDC approval'), ('JOB_CREATE', 'Job create'), ('JOB_CANCEL', 'Job cancel'), ('JOB_REFUND', 'Job refund')], max_length=32)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CHALLENGE_READY', 'Challenge ready'), ('USER_APPROVAL_PENDING', 'User approval pending'), ('SUBMITTED', 'Submitted'), ('PENDING_ONCHAIN', 'Pending onchain'), ('CONFIRMED', 'Confirmed'), ('DENIED', 'Denied'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=32)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('circle_challenge_id', models.CharField(blank=True, max_length=128)),
                ('circle_transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('circle_reference_id', models.CharField(blank=True, max_length=128)),
                ('arc_transaction_hash', models.CharField(blank=True, max_length=66)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
                ('call_data_hash', models.CharField(blank=True, max_length=66)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.walletaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['address'], name='wallets_wal_address_e1eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['blockchain', 'status'], name='wallets_wal_blockch_d58d6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.UniqueConstraint(fields=('user', 'blockchain'), name='uniq_user_blockchain_wallet'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.UniqueConstraint(fields=('blockchain', 'address'), name='uniq_blockchain_wallet_address'),
        ),
        migrations.AddIndex(
            model_name='circletransaction',
            index=models.Index(fields=['user', 'status'], name='wallets_cir_user_id_f3d5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='circletransaction',
            index=models.Index(fields=['circle_challenge_id'], name='wallets_cir_circle__14e99b_idx'),
        ),
        migrations.AddIndex(
            model_name='circletransaction',
            index=models.Index(fields=['arc_transaction_hash'], name='wallets_cir_arc_tra_01c6d4_idx'),
        ),
    ]
